name: Publish Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: $GITHUB_WORKSPACE

      - name: Configure Maven settings
        run: |
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > $GITHUB_WORKSPACE/settings.xml

      - name: Build and publish
        run: mvn -B clean deploy --settings $GITHUB_WORKSPACE/settings.xml
